import { Inter } from "next/font/google";

import type { Metadata } from "next";

import { Header } from "./_components";
import styles from "./layout.module.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${styles.globalLayout}`}>
        <Header></Header>
        <div className={styles.innerHeight}>{children}</div>
      </body>
    </html>
  );
}
