name: "visual reggression testing and unit testing"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm install
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run unit tests
        run: npm run test
      - name: Run interaction tests
        run: npm run test-storybook:coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Chromatic
        run: npm run chromatic -chromatic_token=${{ secrets.CHROMATIC_PROJECT_TOKEN }}
